from __future__ import annotations

import unittest
from pathlib import Path


class FrontendStaticTests(unittest.TestCase):
    def test_frontend_exists_and_uses_safe_v1_copy(self):
        html = Path("frontend/index.html").read_text()
        initial_markup = html.split("<script>", 1)[0]
        self.assertIn("Portfolio Command", html)
        self.assertIn("Saved Portfolios", html)
        self.assertIn("CSV / Excel Import", html)
        self.assertIn("Load Selected File", html)
        self.assertIn("/portfolio-file/convert", html)
        self.assertIn("Workflow Status", html)
        self.assertIn("nextAction", html)
        self.assertIn("command-deck", html)
        self.assertIn("main-board", html)
        self.assertIn("Preview CSV", html)
        self.assertIn("Import & Run Monitor", html)
        self.assertIn("runSimpleWorkflow", html)
        self.assertIn("Massive API Key", html)
        self.assertIn("massiveApiKey", html)
        self.assertNotIn("sentinel.massiveApiKey", html)
        self.assertNotIn("localStorage.setItem(STORAGE_KEYS.massiveApiKey", html)
        self.assertNotIn("body.api_key", html)
        self.assertIn("marketDataConfig", html)
        self.assertIn("function refreshMarketDataConfig", html)
        self.assertIn("/market-data/config", html)
        self.assertIn("function serverMassiveConfigured", html)
        self.assertIn("function massiveReady", html)
        self.assertIn("Server-side Massive key is configured", html)
        self.assertIn("Massive key is missing on the server. Configure MASSIVE_API_KEY before running the monitor.", html)
        self.assertIn("loadPrimaryMarketDataForPortfolio", html)
        self.assertIn("runStatus", html)
        self.assertIn("setWorkflowBusy", html)
        self.assertIn("withSlowNotice", html)
        self.assertIn('data-workspace-mode="monitor"', html)
        self.assertIn("Preview optional", html)
        self.assertIn("Portfolio Tickers", html)
        self.assertIn("Portfolio Monitoring Matrix", html)
        self.assertIn("Stocks By Urgency", html)
        self.assertIn("sortTickerRowsByUrgency", html)
        self.assertIn("tickerUrgency", html)
        self.assertIn("compact-position-list", html)
        self.assertIn("compact-position-row", html)
        self.assertNotIn('body[data-workspace-mode="monitor"] .main-board', html)
        self.assertIn('body[data-page-mode="portfolio"] .stock-detail-section', html)
        self.assertIn("Portfolio page keeps stock detail out of the main workflow", html)
        self.assertIn("renderTickerGauges", html)
        self.assertIn("Stock row gauges", html)
        self.assertIn("Signal direction gauges", html)
        self.assertIn("Trigger Near", html)
        self.assertIn("No buy signal yet", html)
        self.assertIn("The current monitor has not produced a buy signal for this stock.", html)
        self.assertNotIn(">N/A<", html)
        self.assertIn("Ticker Detail", html)
        self.assertIn("chart marker", html)
        self.assertIn("chart-svg", html)
        self.assertIn("tickerDetailUrl", html)
        self.assertIn('target="_blank"', html)
        self.assertIn("Open Details", html)
        self.assertIn("data-page-mode", html)
        self.assertIn("stock-page-nav", html)
        self.assertIn("Classify Unknowns as Investor", html)
        self.assertIn("classify-unknown", html)
        self.assertIn("/classify", html)
        self.assertIn("ticker-type", html)
        self.assertIn('type: get("type") || "investor"', html)
        self.assertIn('["investor", "trader", "index", "unknown"]', html)
        self.assertIn("No saved market data loaded", html)
        self.assertIn("Price Data", html)
        self.assertIn("Clean Chart", html)
        self.assertIn("chart-volume-bar", html)
        self.assertIn("chart-alert-ray", html)
        self.assertIn("chart-viewport", html)
        self.assertIn("preserveAspectRatio", html)
        self.assertIn("data-chart-range", html)
        self.assertIn("data-chart-pan", html)
        self.assertIn("data-chart-zoom", html)
        self.assertIn("chartWindowOffset", html)
        self.assertIn("markerClusterOffsets", html)
        self.assertIn("SMA50", html)
        self.assertIn("SMA150", html)
        self.assertIn("Profit Lock", html)
        self.assertIn("Watched triggers", html)
        self.assertIn("potential_triggers", html)
        self.assertIn("Clean Chart: Price, Volume, SMA50 & SMA150", html)
        self.assertIn("Detailed Chart: Price, Volume, Alerts & Position Levels", html)
        self.assertIn("chart-kpis", html)
        self.assertIn("chart-marker-strip", html)
        self.assertIn("chart-alert-legend", html)
        self.assertIn("chartMarkerTooltip", html)
        self.assertIn("chartMarkerShape", html)
        self.assertIn("chart-marker-shape", html)
        self.assertIn("chart-marker-symbol", html)
        self.assertIn("Exit or violation", html)
        self.assertIn("Bearish distribution", html)
        self.assertIn("Protection / lock", html)
        self.assertIn("chart-volume-average", html)
        self.assertIn("chart-legend", html)
        self.assertIn("Position Metadata Outside Current Price Scale", html)
        self.assertIn("Monitor Receipt", html)
        self.assertIn("Notifications", html)
        self.assertIn("notificationPanel", html)
        self.assertIn("/notifications", html)
        self.assertIn("renderNotifications", html)
        self.assertIn("in-app notifications", html)
        self.assertIn("Stock Snapshot", html)
        self.assertIn("data-chart-mode", html)
        self.assertIn("Methodology Center", html)
        self.assertIn("rule-ledger", html)
        self.assertIn("Current vs Trigger", html)
        self.assertIn("Portfolio Action Queue", html)
        self.assertIn("portfolio-alert-queue", html)
        self.assertIn("additional monitoring rules active", html)
        self.assertIn("ruleDisplayLabel", html)
        self.assertIn("ruleListLabel", html)
        self.assertIn("Investor SMA150 exit", html)
        self.assertIn("Trader SMA50 exit", html)
        self.assertIn("Distribution pressure", html)
        self.assertIn("Recovery violation", html)
        self.assertIn("What the colors and symbols mean", html)
        self.assertIn('id="ruleMeaningPanel" class="rule-meaning-disclosure"', html)
        self.assertNotIn('id="ruleMeaningPanel" class="context-card"', html)
        self.assertIn("activity-drawer", html)
        self.assertNotIn("grid-template-columns: minmax(0, 1fr) minmax(320px, 1fr)", html)
        self.assertIn("Chart Markers & Alert Explanations", html)
        self.assertIn("focusTickerFromActionQueue", html)
        self.assertIn("focusTickerFromActionQueue(focusTicker || firstOpenAlertTicker())", html)
        self.assertIn("Detailed Mode Adds Alert Context", html)
        self.assertIn("ensureInvestorDefaultsForPortfolio", html)
        self.assertIn("await ensureInvestorDefaultsForPortfolio()", html)
        self.assertIn("Applying investor defaults", html)
        self.assertIn("Import & Run Monitor will default them to investor before evaluation", html)
        self.assertIn("Protection violation", html)
        self.assertIn("formatAbsPercent", html)
        self.assertIn("Action now", html)
        self.assertIn("watch-card", html)
        self.assertIn("Recommended Action", html)
        self.assertIn("evidence-toggle", html)
        self.assertIn("renderEvidenceDetails", html)
        self.assertIn("Show Evidence & Data", html)
        self.assertIn("JSON.stringify(evidence || {}, null, 2)", html)
        self.assertNotIn("<label>Evidence</label>", html)
        self.assertNotIn('class="evidence-toggle" open', html)
        self.assertIn("Backfill Massive Data", html)
        self.assertIn("backfill-massive", html)
        self.assertIn("Backfill Online Data", html)
        self.assertIn("backfill-online", html)
        self.assertIn("Mark Placed", html)
        self.assertNotIn("Execute All Exits", html)
        self.assertNotIn("Queue Exit Order", html)
        self.assertNotIn("Auto-trade", html)
        self.assertIn('const DEFAULT_CSV_SOURCE = "No portfolio file loaded";', html)
        self.assertIn("Advanced Manual Controls", initial_markup)
        self.assertNotIn("Sample CSV in editor", initial_markup)
        self.assertNotIn("Demo investor position", initial_markup)
        self.assertNotIn("Demo trader position", initial_markup)
        self.assertNotIn("Load Uploaded Portfolio", initial_markup)
        self.assertNotIn("Load AAPL Chart Scenario", initial_markup)
        self.assertNotIn("Generate Chart Placeholders", initial_markup)
        self.assertNotIn("Backfill AAPL/PLUG Demo", initial_markup)
        self.assertNotIn("Testing Tools", initial_markup)
        self.assertNotIn("local test case", initial_markup)
        self.assertNotIn("local dev server", initial_markup)
        self.assertNotIn("Demo or Placeholder Data", html)

    def test_methodology_center_explains_alerts_in_plain_english(self):
        html = Path("frontend/index.html").read_text()
        self.assertNotIn("Setup data required fired", html)
        self.assertIn("needs setup data", html)
        self.assertIn("Plain English", html)
        self.assertIn("Raw Evidence", html)
        self.assertIn("price/chart watches", html)
        self.assertIn("setup/risk background checks", html)
        self.assertIn("All monitors are active", html)
        self.assertIn("only price-based monitors appear on the chart", html)
        self.assertIn("unusually heavy selling", html)
        self.assertIn("institutional selling pressure", html)
        self.assertIn("15% or more below entry", html)
        self.assertIn("danger zone", html)
        self.assertIn("profit-lock/stop level", html)
        self.assertIn("imported portfolio file did not include", html)

    def test_methodology_center_uses_non_trader_action_language(self):
        html = Path("frontend/index.html").read_text()
        self.assertIn("Long-term trend exit", html)
        self.assertIn("Heavy selling warning", html)
        self.assertIn("15% loss limit warning", html)
        self.assertIn("What is being watched", html)
        self.assertIn("Why this matters", html)
        self.assertIn("What you should do now", html)
        self.assertIn("Technical rule", html)
        self.assertIn("No action needed right now", html)
        self.assertIn("selling is unusually heavy", html)
        self.assertIn("average of the last 150 trading days", html)

    def test_setup_alerts_do_not_score_as_sell_pressure(self):
        html = Path("frontend/index.html").read_text()
        self.assertIn("SETUP_RULE_IDS", html)
        self.assertIn("SELL_RULE_IDS", html)
        self.assertIn("setupOpenCount", html)
        self.assertIn("marketOpenCount", html)
        self.assertIn("Setup", html)
        self.assertNotIn("openCount ? 100", html)
        self.assertNotIn("sell * 0.65", html)

    def test_detail_panels_explain_volume_and_setup_input(self):
        html = Path("frontend/index.html").read_text()
        self.assertIn("Volume vs Normal", html)
        self.assertIn("Normal 50-day volume", html)
        self.assertIn("x normal", html)
        self.assertIn("Volume is compared with the previous 50 loaded bars", html)
        self.assertIn("Save setup data", html)
        self.assertIn("data-save-setup", html)
        self.assertIn("/setup-data", html)
        self.assertIn("Enter the stop/profit-lock level", html)
        self.assertIn("data-alert-tone", html)
        self.assertIn("What this means", html)
        self.assertIn("What to watch", html)

    def test_setup_alerts_are_setup_status_inside_detail_panels(self):
        html = Path("frontend/index.html").read_text()
        self.assertIn("alertStatusForMonitor", html)
        self.assertIn("openAlertsByRule", html)
        self.assertIn("chartAlertsByRule", html)
        self.assertIn('label: "Setup missing"', html)
        self.assertIn("setupDataFieldsMarkup(ticker, row.alert?.explanation?.evidence", html)
        self.assertIn("Setup item, not a buy or sell signal", html)

    def test_market_actions_are_prioritized_ahead_of_setup_tickets(self):
        html = Path("frontend/index.html").read_text()
        self.assertIn("marketAlerts", html)
        self.assertIn("setupAlerts", html)
        self.assertIn("sortAlertsForQueue", html)
        self.assertIn("isSetupAlert", html)
        self.assertIn("Setup needed, not a sell signal", html)
        self.assertIn("Setup missing", html)

    def test_bottom_line_decision_ux_is_present(self):
        html = Path("frontend/index.html").read_text()
        self.assertIn("renderDecisionBottomLine", html)
        self.assertIn("decisionSummaryForRows", html)
        self.assertIn("rowPrimaryReason", html)
        self.assertIn("Bottom Line", html)
        self.assertIn("Primary reason", html)
        self.assertIn("Action required", html)
        self.assertIn("Exit signal", html)
        self.assertIn("Not triggered", html)
        self.assertIn("Setup is secondary", html)
        self.assertIn("triggered-rule-grid", html)
        self.assertIn("passive-watch-list", html)
        self.assertIn("Focus first: market action", html)
        self.assertNotIn("Breach active", html)
        self.assertNotIn("Triggered now", html)

    def test_stock_detail_route_preserves_selected_ticker_before_chart_loads(self):
        html = Path("frontend/index.html").read_text()
        self.assertIn("function setActivePortfolio(portfolio, { preserveSelectedTicker = false } = {})", html)
        self.assertIn("const selectedTicker = preserveSelectedTicker ? state.selectedTicker : null;", html)
        self.assertIn("state.selectedTicker = state.routeTicker;", html)
        self.assertIn("setActivePortfolio(routedPortfolio, { preserveSelectedTicker: true });", html)

    def test_stock_detail_page_prioritizes_chart_before_context_panels(self):
        html = Path("frontend/index.html").read_text()
        self.assertIn("body[data-page-mode=\"stock\"] .main-board", html)
        self.assertIn("body[data-page-mode=\"stock\"] .monitor-context", html)
        self.assertIn("body[data-page-mode=\"stock\"] #notificationPanel", html)
        self.assertIn("order: 0;\n        display: block;", html)
        self.assertIn("order: 1;\n        grid-template-columns: 1fr;", html)

    def test_chart_viewport_renders_before_supporting_kpis_and_legends(self):
        html = Path("frontend/index.html").read_text()
        chart_stage = html[html.index('<div class="chart-stage ${escapeHtml(chartMode)}">'):]
        self.assertLess(chart_stage.index('class="chart-viewport"'), chart_stage.index('class="chart-kpis"'))
        self.assertLess(chart_stage.index('class="chart-viewport"'), chart_stage.index('class="chart-legend"'))

    def test_ticker_detail_renders_chart_before_overview_context(self):
        html = Path("frontend/index.html").read_text()
        detail_template = html[html.index("container.innerHTML = `"):]
        self.assertLess(detail_template.index("${chart}"), detail_template.index("${tickerOverview}"))
        self.assertLess(detail_template.index("${chart}"), detail_template.index("${dataWarning}"))


if __name__ == "__main__":
    unittest.main()
